openapi: 3.0.2
info:
  title: 'BMO Taxonomy'
  version: '1.0'
tags:
  - name: Authentication
    description: Endpoints to authenticate users.
  - name: Prediction
    description: Prediction's endpoints.

paths:
  /api/authentication/login/:
    post:
      operationId: authenticate_login
      description: Logs an user in.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginOutput'
        '400': 
          description: Bad request - input out of format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '404':
          description: User's credentials not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Authentication
      
  /api/authentication/renovate/:
    post:
      operationId: authenticate_renovate
      description: Renovate the user's credentials.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenovateInput'
      responses:
        '200':
          description: Successfully renovate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenovateOutput'
        '400': 
          description: Bad request - input out of format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '406':
          description: User's credentials not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Authentication

  /api/authentication/logout/:
    post:
      operationId: authenticate_logout
      description: Logs an user out.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenovateInput'
      responses:
        '200':
          description: Successfully recover
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutOutput'
        '401': 
          description: Unauthorized - must be logged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Authentication
      security:
        - bearerAuth: [ ]

  /api/prediction/:
    post:
      operationId: prediction_create
      description: Creates a new predict.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionInput'
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictionCreateOutput'
        '400': 
          description: Bad request - input out of format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Prediction
      security:
        - bearerAuth: [ ]

    get:
      operationId: prediction_retrive
      description: Retrives all predictions.
      responses:
        '200':
          description: Successfully retrived
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/PredictOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Prediction
      security:
        - bearerAuth: [ ]

  /api/prediction/{id}/:
    get:
      operationId: prediction_retrive_id
      description: Retrives a prediction by id.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Prediction's id
      responses:
        '200':
          description: Successfully retrived
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/PredictOutput'
        '401': 
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '404':
          description: Prediction's id not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Prediction
      security:
        - bearerAuth: [ ]

    delete:
      operationId: prediction_delete_id
      description: Delete the prediction's entry by id.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Prediction's id
      responses:
        '200':
          description: Successfully retrived
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/PredictionDeleteOutput'
        '401': 
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '404':
          description: Prediction's id not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Prediction
      security:
        - bearerAuth: [ ]

  /api/prediction/{limit}/{offset}/:
    get:
      operationId: prediction_retrive_limited
      description: Retrives all predictions for pagination (limit and offset)
      parameters:
        - in: path
          name: limit
          schema:
            type: integer
          required: true
          description: Limit parameter
        - in: path
          name: offset
          schema:
            type: integer
          required: true
          description: Offset parameter
      responses:
        '200':
          description: Successfully retrived
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/PredictionOutput'
        '400': 
          description: Bad request - input out of format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorOutput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorOutput'
      tags:
        - Prediction
      security:
        - bearerAuth: [ ]
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: User's username
        password: 
          type: string
          description: User's password
        
    LoginOutput:
      type: object
      properties:
        tk_renovation:
          type: string
          description: JWT renovation token
        tk_access:
          type: string
          description: JWT access token
        user:
          type: object
          description: User's information
          $ref: '#/components/schemas/UserOutput'

    RenovateInput:
      type: object
      required:
        - tk_renovation
      properties:
        tk_renovation:
          type: string
          description: JWT renovation token
        
    RenovateOutput:
      type: object
      properties:
        tk_renovation:
          type: string
          description: JWT renovation token
        tk_access:
          type: string
          description: JWT access token
        user:
          type: object
          description: User's information
          $ref: '#/components/schemas/UserOutput'

    LogoutInput:
      type: object
      required:
        - tk_renovation
      properties:
        tk_renovation:
          type: string
          description: JWT renovation token

    LogoutOutput:
      type: object
      properties:
        msg:
          type: string
          description: Describes successfully logged out operation

    PredictionInput:
      type: object
      properties:
        v1:
          type: number
          description: The v1 parameter.
        v2:
          type: number
          description: The v2 parameter.
        v3:
          type: number
          description: The v3 parameter.
        v4:
          type: number
          description: The v4 parameter.
        v5:
          type: number
          description: The v5 parameter.
        v6:
          type: number
          description: The v6 parameter.
        v7:
          type: number
          description: The v7 parameter.
        v8:
          type: number
          description: The v8 parameter.
        v9:
          type: number
          description: The v9 parameter.
        v10:
          type: number
          description: The v10 parameter.
        v11:
          type: number
          description: The v11 parameter.
        v12:
          type: number
          description: The v12 parameter.
        v13:
          type: number
          description: The v13 parameter.
        v14:
          type: number
          description: The v14 parameter.
        v15:
          type: number
          description: The v15 parameter.
        v16:
          type: number
          description: The v16 parameter.
        v17:
          type: number
          description: The v17 parameter.
        v18:
          type: number
          description: The v18 parameter.
        v19:
          type: number
          description: The v19 parameter.
        v20:
          type: number
          description: The v20 parameter.
        v21:
          type: number
          description: The v21 parameter.
        v22:
          type: number
          description: The v22 parameter.
        v23:
          type: number
          description: The v23 parameter.
        v24:
          type: number
          description: The v24 parameter.
        v25:
          type: number
          description: The v25 parameter.
        v26:
          type: number
          description: The v26 parameter.
        v27:
          type: number
          description: The v27 parameter.
        v28:
          type: number
          description: The v28 parameter.
        Amount:
          type: number
          description: The Amount parameter.

    PredictionOutput:
      type: object
      properties:
        id:
          type: integer
          description: The pipeline's id
        v1:
          type: number
          description: The v1 parameter.
        v2:
          type: number
          description: The v2 parameter.
        v3:
          type: number
          description: The v3 parameter.
        v4:
          type: number
          description: The v4 parameter.
        v5:
          type: number
          description: The v5 parameter.
        v6:
          type: number
          description: The v6 parameter.
        v7:
          type: number
          description: The v7 parameter.
        v8:
          type: number
          description: The v8 parameter.
        v9:
          type: number
          description: The v9 parameter.
        v10:
          type: number
          description: The v10 parameter.
        v11:
          type: number
          description: The v11 parameter.
        v12:
          type: number
          description: The v12 parameter.
        v13:
          type: number
          description: The v13 parameter.
        v14:
          type: number
          description: The v14 parameter.
        v15:
          type: number
          description: The v15 parameter.
        v16:
          type: number
          description: The v16 parameter.
        v17:
          type: number
          description: The v17 parameter.
        v18:
          type: number
          description: The v18 parameter.
        v19:
          type: number
          description: The v19 parameter.
        v20:
          type: number
          description: The v20 parameter.
        v21:
          type: number
          description: The v21 parameter.
        v22:
          type: number
          description: The v22 parameter.
        v23:
          type: number
          description: The v23 parameter.
        v24:
          type: number
          description: The v24 parameter.
        v25:
          type: number
          description: The v25 parameter.
        v26:
          type: number
          description: The v26 parameter.
        v27:
          type: number
          description: The v27 parameter.
        v28:
          type: number
          description: The v28 parameter.
        Amount:
          type: number
          description: The Amount parameter.
        Class:
          type: integer
          description: The class predicted.
        
    PredictionDeleteOutput:
      type: object
      properties:
        msg:
          type: string
          description: Describes successfully deletion operation

    PredictionCreateOutput:
      type: object
      properties:
        Class:
          type: integer
          description: The class predicted.

    UserOutput:
      type: object
      properties:
        id:
          type: integer
          description: User's id
        username:
          type: string
          description: User's username
        email:
          type: string
          description: User's email
        date_joined:
          type: string
          description: Creation date of the user's entry
        is_active:
          type: boolean
          description: Whether user is active
        is_superuser:
          type: boolean
          description: Whether user is superuser

    ErrorOutput:
      type: object
      properties:
        msg:
          type: string
          description: Describes an error message